### ISSUE TITLE
GDCR23: Session 3: Outside-In without Mocks

### ISSUE THREAD

**Issue by caichinger** [swkWien/sessions#119]
**Facilitator: Gregor**

- [x] Co-Facilitator: not needed (reach out proactively if you believe support during the session would be helpful)
- [ ] Session Title: ______
- [x] [Schedule](https://docs.google.com/spreadsheets/d/1QG6HFDRYc6USwp6FPPikUBR69i1SRI3obrzPJZdcOZQ/edit?usp=sharing)
- [x] [Slides](https://github.com/swkWien/gdcr23) until Thursday, 2023-11-02
- [ ] What is your first test case? Pls provide input on #116 

---

*Please amend issue to your needs.*

**Comment by gregorriegler** [comment]
Im in vacation until nov 2.
Probably need till nov 3 with preparation.

**Comment by gregorriegler** [comment]
@caichinger I am not able to push my slides

**Comment by ReaSu** [comment]
Let me check.

**Comment by ReaSu** [comment]
I can't find a problem. You are on team Organisers of this account, so you should have all the permissions. Can you call me? (I'll remove my number afterwards) 0650 8043777

**Comment by gregorriegler** [comment]
Mergerequest: https://github.com/swkWien/gdcr23/commit/8480ddd9698f668913a470a6b7052ba1088b0a52
@ReaSu vielen Dank für deinen Support und wertvolle Fragen und Feedback!

**Comment by ReaSu** [comment]
Merged!

**Comment by maosmurf** [comment]
Hi @gregorriegler feel free to call me, we can pair up.
Otherwise you could fork the repo and ping me, then I'll transfer the contents.

EDIT: I now see the MR, but it states "This commit does not belong to any branch on this repository, and may belong to a fork outside of the repository.". @ReaSu  I will take care of this.

Note: anything pushed to `main` is automatically deployed to https://swkwien.github.io/gdcr23/#/title-slide.

Hence we did not yet link our slides. For development, one can uncomment the lines in `index.qmd` (please do not push this file yet)
