### ISSUE TITLE
Coderetreats 2024

### ISSUE THREAD

**Issue by gregorriegler** [swkWien/sessions#132]
Since we didn't do anything so far, what are your wishes/ideas/expectations for this year in terms of coderetreats?
The Idea that I will only see you in person again at the GDCR doesn't feel satisfying @swkWien/organisers

**Comment by ReaSu** [comment]
I would like to see y'all before November too, but don't currently have the resources to organise anything. I welcome your initiative!

**Comment by caichinger** [comment]
@gregorriegler  Thank you for reaching out.

I liked the (bi)monthly **Zero Overhead Coderetreats** we had in the past and would suggest we do that again.
Having the **dates pre-defined** early on helped me plan and remind my of our "learning hours" (dates can then still be adjusted if need be).

I am also open for other ideas but right now I would just go for what felt quite satisfying for me in the past.

---

How about converting this issue into a discussion?

![image](https://github.com/swkWien/sessions/assets/16005912/64bee209-7439-4ff2-a6c6-61bf66501c36) :point_right:

**Comment by codecop** [comment]
Monthly sounds challenging - I like it ;-)

**Comment by ReaSu** [comment]
Thank you for picking this up again. Starting in April sounds good to me, and just like Peter I like the challenge of monthly meetings (no promise I can make every one of them!). If that frequency doesn't work out, we can still go back to bimonthly[1]. Are we thinking Fridays or Saturdays, or switch between the two every month? I can make both work.

Since I don't use my rooms at WKO for anything else, I can use my whole quota for CRs. 

If there is interest I can also ask about meeting at Technikum. I think there's be a new policiy in place where visitors need to register, I can check the exact conditions. Apart from that, anyone can enter the main building Mo-Fri 7:00-21:00; Sat 7:00-13:00. Leaving the building is always possible, so staying longer on a Saturday shouldn't be a problem.

[1] I just checked a dictionary: _bimonthly_ can actually mean _twice a month_ and _every two months_. I mean the latter.

**Comment by maosmurf** [comment]
Hi all and thank you for everything provided so far.
For Saturdays, I can provide facilities at our Office (Zirkusgasse, 1020 Wien)

**Comment by codecop** [comment]
Continued in #134
