### ISSUE TITLE
Setup/Templates for Code Katas

### ISSUE THREAD

**Issue by codecop** [swkWien/sessions#17]
We have a list of projects to clone:
- C++: https://github.com/dertseha/codingdojo-cpp
- Dart: https://github.com/queltos/codingdojo_dart
- Go: https://github.com/dertseha/codingdojo-go
- Java: https://github.com/dertseha/codingdojo-java
- JavaScript: https://github.com/dertseha/codingdojo-js

**Comment by codecop** [comment]
Orga of Dart group translated Java to Dart:
* https://github.com/queltos/codingdojo_dart

**Comment by dertseha** [comment]
Thank for collecting them. I was thinking about this as well and haven't full thought it through yet.

Instead of forking, I'd create a new repo for them and start from scratch; There's no need to keep the history from them. Also (one of my main reasons for having a un-personal template): it would finally remove my private namespace from one or two of these templates; I didn't fully think this through back then and people didn't clean them up ;) )

Furthermore, should that be one repo per language (could become many over time) or simply one "codingdojo-workspace-template" that contains subdirectories per language? I'm tending towards one repo. This would also force people to copy their template out of it, instead of simply committing into the template. (It's still possible, though less likely.)

Thoughts?

**Comment by codecop** [comment]
What is the problem of commiting into the clone of a single setup? It helps because it is already in version control.
Regarding collections, maybe sth like
* https://github.com/coreyhaines/coderetreat
* https://github.com/swkBerlin/kata-bootstraps

**Comment by dertseha** [comment]
A template project should contain only templates. Then again, pull requests with more than just modifications to the templates don't have to be accepted. And how people organize their stuff is up to them of course.

I like the approach of swkBerlin to have a separate folder level for testing frameworks.

**Comment by rolger** [comment]
Emily provides a simple starter project: https://github.com/emilybache/starter
