### ISSUE TITLE
Repeating Hangout/Audio Recording Discussion about topics

### ISSUE THREAD

**Issue by codecop** [swkWien/sessions#41]
New year is full of old and new ideas. I would like to try creating a repeating podcast where we discuss some topic of coding, like SOLID or other topics, allowing guests and publishing the recording. @dertseha I hear you are big on audio equipment? @swkWien/organiser how do you like that idea?

**Comment by dertseha** [comment]
For one I'm all abou this idea, as it is close to my idea of a youtube vlog of two people pairing over some code.

For the folloing points I am referring now to my sketchnotes from the "Podcasting" session from the last SoCraTesAT, hosted by the people from Donau Tech Radio (dtr.fm) :

* The most important thing about such a publication is: Be regular and consistent with your timing. People can work it into their consumption schedule easier if they now when they'll get the next episode.

* The used equipment (technology) is less important, it's the content that matters.
If it's a very interesting topic, people might even endure listening to two people speaking into a laptop microphone. While of course better quality is easier on the ears (eyes), you only need to focus on that when you've established your content. You can start with a decent gaming headset and some VoIP technology and you are good to go.

* Content should be defined, you should think well about it, and it should be something you would want to listen to (watch) yourself.
Related to this is the human language, which also defines your potential audience. DTR for instance conciously decided on German because they can keep their Austrian (upper austria) accent.

* Then comes the production chain (format, recording, editing, and publication). Details on that when we get more concrete :)

Personal thoughts:
Speaking from my own experience, the focus must definitely be first on content rather than the used equipment/technology. I can and would support in the technology part, yet I found myself neglecting content during pre-production, so I'll restrain myself at this point :)

So, did you already have a set of topics in mind the broadcast should focus on?

**Comment by codecop** [comment]
Thank you for participating. I don't care for the equipment - was just teasing you. I agree content is king. I had no special content in mind, just discussing some interesting topics. Also I agree, topics should be the topics I would like to hear about. What would you like to hear about? (I am in a kind of topic fatigue right now, I can't say). On the other hand, me being me, I guess it would be around clean code, readability, design and such.

**Comment by codecop** [comment]
@duffleit please contribute your ideas/questions we talked about during Voxxed Days

**Comment by duffleit** [comment]
Sounds like a deja-vu. Had some similar idea a while ago, but couldn't find enough people doing this with me to provide a continuous stream of new episodes. As @dertseha mentioned already, I think the most important part in doing things like this is being regular. (same can be applied for blogging - obviously fail here terribly :D )

> What would you like to hear about?

If I listen to podcasts I'm not so picky about the topic itself. Primarily I'm interested in the people, which participate. For example one of the greatest podcast I listened to recently was about "The future of Angular" by John Papa. Even if I'm not deep into Angular, and personally prefer stuff like React or Vue more, it was amazing, as John is probably one of the leading experts in the angular-stack and had a lot of interesting things to explain and talk about. Therefore I would not limit myself too much to a specific topic, as I think it's important to involve the right people which have something interesting stories to tell or knowledge to share. I have a few people in my mind that I've met mostly at conferences or training that meet those requirements. Maybe we could also focus especially on people from Vienna/Austria.

I have planned to be at the next Dojo by Bojan, we could there match our ideas for a podcast or some similar format.

**Comment by dertseha** [comment]
Welp, the dojo came, passed, and nothing was discussed ;)

What could help is making one or two unaired pilots. i.e., simply meet up via some VoIP technology, and talk, timeboxed. This way we're less concerned about making it public, and focus more on our own interaction and content. Afterwards we can decide whether this could be something worth repeating and publishing.

As for the content: I don't listen to podcasts, and watch youtube videos only selectively (typically talks).
(Several unwritten thoughts pass - trying to serialize)
For some reason the title "Code for Sunday" (or a derivative of it) comes to my mind - being a play on the German "[Das Wort zum Sonntag](https://de.wikipedia.org/wiki/Das_Wort_zum_Sonntag)". On one part based on my typical drive to jest with words, I also associate that with the general topic-bubble of clean code and other non-functional, inner-quality requirements on code. Perhaps, to remove the religious connotation, which bears flame-potential from the get-go, this bubble can also be seen as a cultural thing. You have to have a certain culture of people - culture in terms of repeated habits - to thrive with ideas like Clean Code. Thus I present (propose):

"Code Culture" - "An audio/visual reference about the developers own quality"

Words dissected:
* "Code Culture" - as described above. Furthermore settles that it will not be primarily about technologies (although they still support the discussed topics).
* "Audio/Visual" - it is pitched as a podcast, yet I could also imagine supplying some video then and again. Could also be removed altogether: "A reference..."
* "reference" - Alternatives that I had in mind: "publication", "guide". I settled on "reference" as I'd like to see such a publication as a possible source for inspiration, not "law" (Because who are "we" - or anyone else - to govern what the culture shall be). At the very least, we could just be talking about other people's publications (audio or video) and rate & link them. I'd like to avoid a "preaching to the choir" style, and be accessible to people with different culture (mindsets).
* "the developers own quality": Again a play with words in the sense that it could mean more than just one specific thing. One interpretation: "Quality of the developer" - what it means to make a "good" developer. Other interpretation "Quality of the developers product" (cue adage about next developer being an axe-wielding murderer...)

All in all, this frames the content - both quite strict, and lose enough:
* We wouldn't be discussing the next big JavaScript UI framework, yet could take react.js (and related) as an example for the change of thinking regarding event-driven code, and how to make it manageable.
* We wouldn't be discussing nitpicky stuff like indentation, yet discuss auto-code-formatting
* We wouldn't be discussing Jira, yet elaborate on the importance of commit messages and their linking to issue trackers
* This still allows also to talk about the culture, or rather the style, of various programming languages.

Also, "Code Culture" fits well to ideas of "Softwerkskammer", and even dreaded abbreviations are not tongue breaker: "This is X and Y, reporting live for SKCCR, ..." :P
(Yes, I also tend towards an English publication, to avoid the inevitable Denglisch - and because we're rather international here in Vienna :) )

So, for any topics you had in mind, would they fit? If you didn't have any topics in mind, does the title give you ideas/wishes?

**Comment by paulroho** [comment]
I very much like the idea of a podcast (since I am just another guy thinking about doing one for myself for years now).
And while I can relate to many of the thoughts brought up above, I would strongly advocate for a more lightweight and test driven approach:
* Schedule a 4+ hours meeting with everyone interested
* Make sure some basic audio equipment is in place. No fancy stuff needed here, maybe just a jabra on a notebook or alike. In that phase we should not be distracted by this kind of tech stuff.
* Use 30' to an hour to brainstorm on
   * IN: Things we want to have in it to make it feel useful
   * OUT: Things we do not want to have in it
* Agree a *basic* set of INs and OUTs.
* Use 15' to 30' to brainstorm and agree on a test-recording
* Make a very rough sketch of the flow of the podcast (or leave that out ATM at all)
* Press record and start talking
* Use the last 30' or so for a retro
Then everybody goes home, listens to the recording, reflects on the session and plan for the future.

**Comment by dertseha** [comment]
...sounds like a "stop starting and start finishing" :P
Thank you, Paul

**Comment by gerykiss86** [comment]
How about next week, to do this `4+ hours meeting` at ~17:00? @dertseha @paulroho @codecop and everyone else who is interested? 

:one: Tuesday (15.2, 17:00)
:two: Wednesday (16.2, 17:00)
:three: Thursday (17.2, 17:00)
:four: Friday (18.2, 17:00)

**Comment by dertseha** [comment]
Thank you for the next initiative :)
I have time only on Tuesday (We-Fr is conference), yet I am offering a conference room for this (including USB conference microphone) at FRQ.

**Comment by dertseha** [comment]
@codecop will you make it on Tuesday? 
I'd like to know whether I should be reserving a room - If there's no other proposal - You're the one that started this, so I think you should be present :).

**Comment by dertseha** [comment]
Peter sent me a message that he has no time for the whole week.
New proposal, @duffleit  - or do you want to make one, @codecop ?

**Comment by duffleit** [comment]
The more opinions and inputs the better. How about Tuesday the 22th?

**Comment by dertseha** [comment]
Also: Is it necessary to be together in person (for the prototype), or would an online meeting suffice? Wouldn't even have to be with cameras.

I know that a this option strips away some basic conversation tools (body language and so forth), though, if we can't even agree on a (physical) meeting for the prototype, how would we ever get a _regular_ schedule in place?

**Comment by paulroho** [comment]
@dertseha, I agree with you regarding the regular issues of the podcast. But for the kick off I would **strongly** vote for a face-to-face meeting. It's unparalleled bandwidth.

**Comment by codecop** [comment]
thank you for trying to keep me in the loop. This May is crazy unfortunately

**Comment by duffleit** [comment]
@codecop, could you come up with some proposal for june?

**Comment by codecop** [comment]
As discussed with Paul, please go ahead without me for now. I will support everything that is created/decided.

**Comment by duffleit** [comment]
Ok, how about Tuesday the 19th at about 18h @dertseha and @paulroho ? Can you still manage to get a room for us @dertseha ?

**Comment by paulroho** [comment]
Cool, is fine for me.

**Comment by dertseha** [comment]
19th is OK for me. Yes, I should be able to provide a meeting room.
Two guests then, @duffleit and @paulroho , from 6pm. I hope though that we finish at around 9pm latest (contrary to the initial pitch of 4h+ from you, Paul...) .

**Comment by paulroho** [comment]
Cooly mooly, so be it!
#awesomized

**Comment by dertseha** [comment]
I've registered you two as guests, to arrive at around 6pm. Room is reserved as well.
@duffleit you know where FRQ is / how to get there?

**Comment by dertseha** [comment]
I'm about to distribute the pilot recording (not meant for publication) together with the notes with direct messages.

General definitions:
* We set out to do this once per month, for one year (= 12 recordings) 
* Audience: For people who work on/with code.
* Language: English
* Scope (topics): loosely related to "Building software right", crafting, TDD, ... Guided by agile manifesto (we value X over Y - so if a tool is relevant, it might be a topic)
* Duration: 30-45 min
* Range: From "We want to discuss questions we have ourselves" to "We want to explain things to others".
* Options: Interviews, Reading circle & book discussion
* Considerations:
  * Think of a structure (i.e. a topic, some light refreshment, another topic, ...)

Homework:
* More brainstorming on topics (see notes)
  * find format to store topic roadmap
* Settle on name
* Settle on next recording date (-> July)
* Find publication platform
* Prepare better recording setup (my own task - the initial recording works, though I'm not happy with the quality ;) )

What did I miss?

**Comment by dertseha** [comment]
Can be closed. Podcast available here: https://developermelange.github.io/

Although the podcast about software engineering and building great products would fit into the spirit of Softwerkskammer, it was deemed not to be published under its banner, because, quoting, "SWK Wien is just Coding Dojos".
